server:
  port: 0

spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_db
    username: root
    password: Bhupen15@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
      job:
        enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka/

logging:
  level:
    root: info
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log

customer:
  data:
    file:
      path: src/main/resources/customers-data.csv
      header: customerId,firstName,lastName,email,gender,contactNumber,country,dateOfBirth
    save:
      chunk:
        size: 250
