
server:
  port: 8072

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka/
  

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**, /api/admin/**
          filters:
            - GwyAuthFilter
        - id: URL-SERVICE
          uri: lb://URL-SERVICE
          predicates:
            - Path=/api/url/**
          filters:
            - GwyAuthFilter
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
          filters:
            - GwyAuthFilter
infra:
  security:
    # NONE, BASIC, JWT
    type: NONE
logging:
  level:
    root: info
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log

