server:
  port: 0

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_db
    username: root
    password: Bhupen15@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

infra:
  security:
    # NONE, BASIC, JWT
    type: NONE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka/

logging:
  level:
    root: info
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log
